version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "demoSamApp"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1hhxnqzvdkow7"
s3_prefix = "demoSamApp"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
